version: '3'

services:

  # The production Teamscale instance.
  v7.7:
    # This targets the latest 7.7 release. Altenatively use e.g. 'cqse/teamscale:7.7.0' to point to a specific release.
    image: 'cqse/teamscale:7.7.latest'
    restart: unless-stopped
    # The working directory within the docker container, where all data is stored.
    # This is different from the installation directory `/opt/teamscale`
    working_dir: /var/teamscale
    volumes:
      # Use the `v7.7` folder as working directory
      - ./v7.7/:/var/teamscale/
      # Mount the custom checks (if present) as read-only within the working directory
      # - ./custom-checks:/var/teamscale/custom-checks:ro
      # Also external libraries (such as the SAP Java Connector) should be mounted as read-only within the installation directory
      # - ./lib-ext:/opt/teamscale/lib-ext:ro
    environment:
      # Specify the timezone of the host system
      TZ: "Europe/Berlin"
      # The Teamscale memory limit (alternative to storing it in jvm.properties)
      TEAMSCALE_MEMORY: 4G
      # You can specify Teamscale properties here
      # teamscale.properties is not considered at all when this environment variable is set
      TS_PROPERTIES: |-
        database.type=leveldb
        engine.workers=2
        instance.name=v7.7
      # You can also specify additional options that should be appended to the JVM command line
      # TEAMSCALE_OPTS: >-
      #   -Dcom.teamscale.mergerequest.disable-automatic-webhook-creation=true

  # The staging Teamscale instance.
  v7.8:
    image: 'cqse/teamscale:7.8.latest'
    restart: unless-stopped
    working_dir: /var/teamscale
    volumes:
      - ./v7.8/:/var/teamscale/
      # Mount the custom checks (if present) as read-only within the working directory
      # - ./custom-checks:/var/teamscale/custom-checks:ro
      # Also external libraries (such as the SAP Java Connector) should be mounted as read-only within the installation directory
      # - ./lib-ext:/opt/teamscale/lib-ext:ro
    environment:
      TZ: "Europe/Berlin"
      TEAMSCALE_MEMORY: 4G
      TS_PROPERTIES: |-
        database.type=leveldb
        engine.workers=2
        instance.name=v7.8

  # The nginx server that proxies the Teamscale instances
  nginx:
    image: 'nginx:alpine'
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - '80:80'
      - '443:443'

